### ISSUE TITLE
identity verification

### ISSUE THREAD

**Issue by mattiaborsoi** [websharks/woocommerce-intercom-pro#31]
So I've been doing quite a bit of digging here into this plugin. Unfortunately, this isn't actually an official integration with Intercom at all, as an official integration will never ask you for your Access Token, as it seems that WooCommerce Pro seems to do 🤔
Recently Intercom started using identity verification, which this plugin doesn't support and therefore won't load the chat for logged in users. Also won't transmit the purchase information over to Intercom at all.

These Access Tokens should be treated in the same way as passwords, and should never be handed out to external parties like this, as they get access to your customer's personal information and can do what they like with it. 

I would actually advise the developers to apply for OAuth with Intercom, which they can do here https://developers.intercom.com/docs/applying-for-oauth.

In the meantime, the fastest and safest way to resolve this issue would be to stop using the WooCommerce Pro integration, as it is the main cause of the issues at play here. 

I know this isn't an ideal solution, but for your own security it really is the best solution right now!

**Comment by jaswrks** [comment]
Closing. This was resolved in a private ticket.

*Takeaway:* WooCommerce Intercom Pro is not an external third party application, because it runs on your site and does not connect to our servers. So configuring an access token is perfectly OK. Also, it's optional. It's there to send details about purchases on your site to Intercom, allowing you to build and maintain a history of customer activity inside Intercom as a convenience.
